name: Fast C/C++ Validation

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  check-c-cpp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: Check C/C++ Syntax and Logic
        run: |
          cppcheck --enable=warning,style,performance,portability \
                   --error-exitcode=1 \
                   --inline-suppr \
                   --suppress=missingInclude \
                   --suppress=missingIncludeSystem \
                   native/
